export const products = [
  {
    id: "bedsheet-luxury-cotton",
    name: "Luxury Cotton Bedsheet Set",
    description:
      "Experience the ultimate comfort with our 100% Egyptian cotton bedsheet set. Includes flat sheet, fitted sheet, and two pillowcases.",
    price: 129.99,
    category: "Bedsheets",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    colors: ["#FFFFFF", "#F5F5DC", "#D3D3D3", "#87CEEB"],
    sizes: ["Twin", "Full", "Queen", "King"],
    rating: 4.8,
    reviews: 124,
    features: ["100% Egyptian cotton", "600 thread count", "Wrinkle-resistant", "Fade-resistant", "Machine washable"],
    specifications: [
      { name: "Material", value: "100% Egyptian Cotton" },
      { name: "Thread Count", value: "600" },
      { name: "Care", value: "Machine wash cold, tumble dry low" },
      { name: "Includes", value: "Flat sheet, fitted sheet, 2 pillowcases" },
      { name: "Origin", value: "Imported" },
    ],
  },
  {
    id: "towel-premium-bath",
    name: "Premium Bath Towel Set",
    description:
      "Wrap yourself in luxury with our premium bath towel set. Made from high-quality cotton for maximum absorbency and softness.",
    price: 79.99,
    category: "Towels",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    colors: ["#FFFFFF", "#87CEEB", "#FFB6C1", "#90EE90"],
    rating: 4.6,
    reviews: 98,
    features: [
      "100% Turkish cotton",
      "600 GSM weight",
      "Highly absorbent",
      "Quick-drying",
      "Set includes 2 bath towels, 2 hand towels, 2 washcloths",
    ],
    specifications: [
      { name: "Material", value: "100% Turkish Cotton" },
      { name: "Weight", value: "600 GSM" },
      { name: "Dimensions", value: 'Bath: 30"x54", Hand: 16"x28", Washcloth: 12"x12"' },
      { name: "Care", value: "Machine wash warm, tumble dry low" },
      { name: "Origin", value: "Imported" },
    ],
  },
  {
    id: "pillow-case-silk",
    name: "Silk Pillowcase Set",
    description:
      "Elevate your sleep experience with our 100% mulberry silk pillowcases. Gentle on hair and skin, these pillowcases reduce friction and help maintain moisture.",
    price: 59.99,
    category: "Pillow Cases",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    colors: ["#FFFFFF", "#F5F5DC", "#FFB6C1", "#000000"],
    sizes: ["Standard", "Queen", "King"],
    rating: 4.9,
    reviews: 156,
    features: [
      "100% mulberry silk",
      "22 momme weight",
      "Reduces hair breakage",
      "Prevents sleep creases",
      "Hypoallergenic",
    ],
    specifications: [
      { name: "Material", value: "100% Mulberry Silk" },
      { name: "Weight", value: "22 Momme" },
      { name: "Closure", value: "Hidden zipper" },
      { name: "Care", value: "Hand wash or delicate machine cycle, line dry" },
      { name: "Origin", value: "Imported" },
    ],
  },
  {
    id: "blanket-weighted",
    name: "Therapeutic Weighted Blanket",
    description:
      "Experience deeper, more restful sleep with our premium weighted blanket. The gentle, evenly distributed pressure helps reduce anxiety and promotes relaxation.",
    price: 149.99,
    category: "Blankets",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    colors: ["#D3D3D3", "#87CEEB", "#FFB6C1"],
    sizes: ["10lbs", "15lbs", "20lbs"],
    rating: 4.7,
    reviews: 83,
    features: [
      "Premium glass bead filling",
      "100% cotton cover",
      "Even weight distribution",
      "Reduces anxiety",
      "Promotes deeper sleep",
    ],
    specifications: [
      { name: "Material", value: "100% Cotton cover, glass bead filling" },
      { name: "Weight Options", value: "10lbs, 15lbs, 20lbs" },
      { name: "Dimensions", value: '48"x72" (Twin size)' },
      { name: "Care", value: "Removable cover is machine washable" },
      { name: "Recommended", value: "Choose a blanket ~10% of body weight" },
    ],
  },
  {
    id: "bedsheet-organic-bamboo",
    name: "Organic Bamboo Sheet Set",
    description:
      "Experience the cool, silky feel of our bamboo sheets. Naturally temperature-regulating and eco-friendly, these sheets are perfect for hot sleepers.",
    price: 119.99,
    category: "Bedsheets",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    colors: ["#FFFFFF", "#F5F5DC", "#D3D3D3"],
    sizes: ["Twin", "Full", "Queen", "King"],
    rating: 4.5,
    reviews: 76,
    features: [
      "100% organic bamboo viscose",
      "300 thread count",
      "Temperature regulating",
      "Moisture-wicking",
      "Eco-friendly",
    ],
    specifications: [
      { name: "Material", value: "100% Organic Bamboo Viscose" },
      { name: "Thread Count", value: "300" },
      { name: "Care", value: "Machine wash cold, gentle cycle, tumble dry low" },
      { name: "Includes", value: "Flat sheet, fitted sheet, 2 pillowcases" },
      { name: "Origin", value: "Sustainably manufactured" },
    ],
  },
  {
    id: "towel-microfiber-gym",
    name: "Quick-Dry Microfiber Gym Towels",
    description:
      "Perfect for the gym, travel, or outdoor activities. These lightweight, ultra-absorbent microfiber towels dry 3x faster than cotton towels.",
    price: 34.99,
    category: "Towels",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    colors: ["#000000", "#87CEEB", "#FF0000", "#90EE90"],
    rating: 4.4,
    reviews: 52,
    features: [
      "Ultra-absorbent microfiber",
      "Quick-drying",
      "Lightweight and compact",
      "Antimicrobial treatment",
      "Set includes 3 towels",
    ],
    specifications: [
      { name: "Material", value: "80% Polyester, 20% Polyamide" },
      { name: "Dimensions", value: '40"x20"' },
      { name: "Weight", value: "220 GSM" },
      { name: "Care", value: "Machine wash cold, no fabric softener, tumble dry low" },
      { name: "Features", value: "Hanging loop, antimicrobial treatment" },
    ],
  },
  {
    id: "pillow-case-satin",
    name: "Luxury Satin Pillowcase Pair",
    description:
      "Enjoy the benefits of satin at an affordable price. These pillowcases reduce hair breakage and facial creases while providing a cool, comfortable sleep surface.",
    price: 29.99,
    category: "Pillow Cases",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    colors: ["#FFFFFF", "#F5F5DC", "#FFB6C1", "#000000", "#87CEEB"],
    sizes: ["Standard", "Queen", "King"],
    rating: 4.3,
    reviews: 118,
    features: [
      "High-quality polyester satin",
      "Reduces hair frizz and breakage",
      "Prevents facial creases",
      "Envelope closure",
      "Budget-friendly alternative to silk",
    ],
    specifications: [
      { name: "Material", value: "100% Polyester Satin" },
      { name: "Closure", value: "Envelope style" },
      { name: "Care", value: "Machine wash cold, gentle cycle, tumble dry low" },
      { name: "Quantity", value: "Set of 2 pillowcases" },
    ],
  },
  {
    id: "blanket-sherpa-throw",
    name: "Reversible Sherpa Throw Blanket",
    description:
      "The perfect cozy companion for chilly evenings. This reversible throw features soft microfiber on one side and plush sherpa fleece on the other.",
    price: 49.99,
    category: "Blankets",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    colors: ["#D3D3D3", "#87CEEB", "#FFB6C1", "#F5F5DC"],
    rating: 4.8,
    reviews: 205,
    features: [
      "Reversible design",
      "Microfiber front, sherpa fleece back",
      "Ultra-soft and warm",
      "Lightweight yet cozy",
      "Perfect for couch, bed, or travel",
    ],
    specifications: [
      { name: "Material", value: "100% Polyester (Microfiber and Sherpa)" },
      { name: "Dimensions", value: '50"x60"' },
      { name: "Weight", value: "Medium weight" },
      { name: "Care", value: "Machine wash cold, tumble dry low" },
      { name: "Origin", value: "Imported" },
    ],
  },
]
